# Create the environment with:
# conda env create -f docs_environment.yaml

name: 
  docs-pyhanami-env_v0.2.0
channels:
  - conda-forge
dependencies:
  - python==3.11.5
  - cartopy
  - pip
  - pip:
    - -r docs_requirements.txt