[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "pyhanami"
version = "0.1.0"
authors = [
    {name = "Marta Alerany Solé", email = "marta.alerany@bsc.es"},
    {name = "Kai Keller", email = "kai.keller@bsc.es"},
    {name = "Masuo Nakano", email = "masuo@jamstec.go.jp"}
]

description = "pyhanami is a tool designed to evaluate the replicability and projection skill of Earth System Models"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["Earth System Models", "replicability", "projection skill"]
classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: Unix",
    "Operating System :: Microsoft",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Topic :: Scientific/Engineering :: Atmospheric Science"
]

requires-python = ">=3.7"
dependencies = [
    "cartopy",
    "cmocean",
    "eofs",
    "matplotlib",
    "netCDF4",
    "numpy",
    "pandas",
    "pint",
    "scipy",
    "xarray",
    "xesmf",
]


[project.urls]
homepage = "https://earth.bsc.es/gitlab/ces/hanami/pyhanami"
repository = "https://earth.bsc.es/gitlab/ces/hanami/pyhanami"
documentation = "https://earth.bsc.es/gitlab/ces/hanami/pyhanami"